version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
      POSTGRES_DB: db

    ports:
      - 5432:5432

  backend:
    restart: on-failure:10
    depends_on:
      - db
    image: wallet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  backend_migrate:
    restart: 'no'
    depends_on:
      - db
    image: wallet
    command: 'python /Wallet/Wallet/manage.py migrate'
    ports:
      - 8001:8000

  backend_loaddata:
    restart: 'no'
    depends_on:
      - db
      - backend_migrate
      - backend
    image: wallet
    command: 'python /Wallet/Wallet/manage.py loaddata db.json'
    ports:
      - 8002:8000