# Generated by Django 4.0.3 on 2022-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_from',
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_from',
            field=models.ManyToManyField(related_name='operation_from', to='backend.account'),
        ),
    ]
