# Generated by Django 4.0.3 on 2022-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_operation_operation_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default='2011-11-11'),
        ),
    ]
