# Generated by Django 4.0.3 on 2022-03-12 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 12)),
        ),
    ]
